name: Build CV.pdf

on:
  push:
    branches: [ master ]
    paths:
      - '**.json'
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout json-resume2altacv
      uses: actions/checkout@v2.3.2
      with:
        repository: eitchtee/json-resume2altacv
        path: builder
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout eitchtee.github.io
      uses: actions/checkout@v2.3.2
      with:
        path: site

    - name: Setup Python
      uses: actions/setup-python@v2.1.2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r builder/requirements.txt
    
    - name: Run builder
      run: |
        python builder/builder.py site/files/config-pt.yaml
        python builder/builder.py site/files/config-en.yaml
